### ISSUE TITLE
Server-Side-Rendering

### ISSUE THREAD

**Issue by YeonV** [HubSpot/cms-react-boilerplate#13]
First of all: Great Project!! Thank you very much!!

Is SSR already included or planned?

**Comment by TheWebTech** [comment]
Hey there, thank you for the question. Right now HubSpot currently only supports HubL server side rendering. We are always looking at ways to improve the developer experience and that includes enabling developers to use tools and languages they're more familiar with.

Curious, if you were able to server-side render React inside the HubSpot CMS:
- Are you imagining something like an existing theme with modules, template, etc but using React instead of HubL?

-  Are you imagining something more like a JS application along the lines of next.js, Remix, etc that created/deployed pages directly instead of having templates? 

- Are you imagining something else?

**Comment by TheWebTech** [comment]
In-case others stumble upon this.

In beta is server side rendering with React in HubSpot:
https://github.com/HubSpot/cms-js-building-block-examples
