### ISSUE TITLE
Hubspot module with react-router-dom

### ISSUE THREAD

**Issue by wiredmartian** [HubSpot/cms-react-boilerplate#39]
We're currently working on a SPA app using this template. We're trying to create a template in Hubspot that will have only one module inside which is the SPA. 

I was testing it earlier using the [react-router-dom](https://www.npmjs.com/package/react-router-dom) and it wasn't working. I was just wondering if it's possible to do this?
Can I have a router inside my module?

**Comment by wiredmartian** [comment]
I managed to get to work with HashRouter

``` js
const targetModulesData = document.querySelectorAll(
  '.cms-react-boilerplate > script[type="application/json"]',
);
targetModulesData.forEach(({ dataset, textContent }) => {
  const root = document.getElementById(`App--${dataset.moduleInstance}`);

  return ReactDOM.render(
      <HashRouter>
        <Routes>
        <Route path='/' element={<App
          portalId={dataset.portalId}
          moduleData={JSON.parse(textContent)}
          moduleInstance={dataset.moduleInstance}
        />}>
          <Route path='page-1' element={<Page1/>}/>
          <Route path='page-2' element={<Page2/>}/>
          <Route path="*"
            element={
              <main style={{ padding: "1rem" }}>
                <p>There's nothing here!</p>
              </main>
            }
          />
        </Route>
        </Routes>
      </HashRouter>,
    root,
  );
});
```

**Comment by AustinSpinazze** [comment]
@wiredmartian I also ran into this problem today. I believe it has something to do with the fact that it is technically a server-side rendered React app instead of a client-side rendered React app. Weirdly for me, this solution did not work using HashRouter and the only difference I did is that I have my Routes and Route components in my App.js file but there is no reason that should not work. Could you re-open this issue for further investigation?
